### ISSUE TITLE
kSkimming_run2_cfg.py no longer works

### ISSUE THREAD

**Issue by anehrkor** [KappaAnalysis/Kappa#38]
Hi,

I just tried to run kSkimming_run2_cfg.py locally and get an error from datasetsHelper2015.py:
`pd_name, details, filetype = sample.strip("/").split("/")` (line 37)
`ValueError: need more than 1 value to unpack`

I'm fairly sure that this is because datasets.json changed drastically. Previously, we used the dbs name of a file for the dictionary while now it seems to be the nick which does not have any `/` characters.

I think some code cleanup is necessary on a short timescale because right now it's not clear what can still be used and what can't. Maybe some files are now deprecated anyhow?

Cheers,
Alex

**Comment by ArturAkh** [comment]
Hi Alex,

Should be solved by now:

https://github.com/KappaAnalysis/Kappa/commit/fb8c205b8bc3b2a8a34341c3373a54d6c2f63993

I've removed the old kappa skimming config and now it should work with the same name.

I change slightly the syntax for the "testfile" to leave it to the user to choose the right access protocol:

file:// for local files, root://....//store/... for xrootd (explicit xrootd server) and /store/... for official xrootd access.

To run the skimming config I ran for example:

cmsRun Kappa/Skimming/higgsTauTau/kSkimming_run2_cfg.py globalTag=80X_mcRun2_asymptotic_2016_TrancheIV_v7 testfile="/store/mc/RunIISummer16MiniAODv2/SUSYGluGluToHToTauTau_M-200_TuneCUETP8M1_13TeV-pythia8/MINIAODSIM/PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/60000/A8AC33C3-6CD7-E611-BD01-02163E0135A6.root" maxevents=10000

Since I haven't observed any problems regarding the MVA MET corrections, I've put it back into the config.

Cheers,

Artur
