### ISSUE TITLE
Gen status und flags

### ISSUE THREAD

**Issue by JoramBerger** [KappaAnalysis/Kappa#9]
The different status codes from different generators and the status flags could be unified in ĸappa. Are both status and flags needed? Is there redundancy? There are frequent discussions on hn-cms-generators.

**Comment by thomas-mueller** [comment]
Without to much insight, isn't it useful to just copy the values in Kappa and keep the possibility to have the same values on analysis level as all other groups at CERN?

**Comment by JoramBerger** [comment]
That's what is done currently and it is reasonable. "All other groups at CERN" is difficult because they differ quite a bit. However, among generator guys, this misery of differing standards is being taken care of and the standards are a moving target. It would make sense to follow that up. I think the addition of the flags is going in the right direction as it provides a unified criterion for 'hard interaction' particles for example which simply didn't exist before. I just wanted to mention that this is moving and should be followed up. The situation might improve.

**Comment by JoramBerger** [comment]
Some references:
https://hypernews.cern.ch/HyperNews/CMS/get/generators/2755.html
https://hypernews.cern.ch/HyperNews/CMS/get/generators/2629.html
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/PhysicsTools/HepMCCandAlgos/interface/MCTruthHelper.h

Perhaps Fabio can tell whether this discussion is already closed by the linked status flags or still moving. If there is no interest in keeping this reminder, I am also fine if you close the issue right away. One question for me is still: Are the status flags replacing the generator-specific status or just additional information?

**Comment by fcolombo** [comment]
My way of seeing this, is that the generator flag are a useful, generator-independent, replacement for the status codes. As far as I can see from the HTauTau analysis, they will be more and more useful (and used) in future. Of course, since they are a fairly recent development in CMSSW, they are available only from 74X onwards.
To me it makes sense to still keep both in Kappa, at least for backwards compatibility.
At the moment, what is implemented in Kappa is a 1:1 translation of a subset of these flags
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/DataFormats/HepMCCandidate/interface/GenStatusFlags.h#L18-L32
and of these user-friendly functions, which are built on top of generator flags and status codes
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/DataFormats/HepMCCandidate/interface/GenParticle.h#L54-L103

I said "a subset" because I explicitly didn't want to save the ones whose usage is discouraged (or considered as "dangerous") by the developers themselves.
If this is a moving target (and this is also my impression), we have to keep an eye on each CMSSW release that we will use, check if new flags are added/removed or if the user-friendly functions change their return values, and consequently act on Kappa.

**Comment by JoramBerger** [comment]
Thanks for the information. Together with the mail by Fabio about the reasoning behind the flags and the status codes, I would say it is sufficiently discussed and well done for the moment. I close this issue – feel free to reopen it if there is more to discuss.
